# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  # orderer0.org1.example.com:
  # orderer1.org1.example.com:
  peer0.org1.example.com:
  peer1.org1.example.com:


networks:
  fabric:

services:

  peer0.org1.example.com:
    container_name: peer0.${PEER_DOMAIN}
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.example.com
    networks:
      - fabric
    extra_hosts: &hosts
      - 'peer0.${ID1}:${ID1_HOSTS}'
      - 'peer1.${ID1}:${ID1_HOSTS}'
      - 'peer0.${ID2}:${ID2_HOSTS}'
      - 'peer1.${ID2}:${ID2_HOSTS}'
      - 'peer0.${ID3}:${ID3_HOSTS}'
      - 'peer1.${ID3}:${ID3_HOSTS}'

  peer1.org1.example.com:
    container_name: peer1.${PEER_DOMAIN}
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.example.com
    networks:
      - fabric
    extra_hosts:
      *hosts

  cli.peer0:
    container_name: cli.peer0
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.${PEER_DOMAIN}:7051
      - CORE_PEER_LOCALMSPID=${PEER_LOCALMSPID}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${PEER_DOMAIN}/peers/peer0.${PEER_DOMAIN}/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${PEER_DOMAIN}/peers/peer0.${PEER_DOMAIN}/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${PEER_DOMAIN}/peers/peer0.${PEER_DOMAIN}/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${PEER_DOMAIN}/users/Admin@${PEER_DOMAIN}/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c "cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && bash"
    volumes:
        - /var/run/:/host/var/run/
        - ./../../../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on: &depend_service
      - orderer0.org1.example.com
      - orderer1.org1.example.com
      - peer0.org1.example.com
      - peer1.org1.example.com
    networks:
      - fabric
    extra_hosts:
      *hosts

  cli.peer1:
    container_name: cli.peer1
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.${PEER_DOMAIN}:8051
      - CORE_PEER_LOCALMSPID=${PEER_LOCALMSPID}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${PEER_DOMAIN}/peers/peer1.${PEER_DOMAIN}/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${PEER_DOMAIN}/peers/peer1.${PEER_DOMAIN}/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${PEER_DOMAIN}/peers/peer1.${PEER_DOMAIN}/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${PEER_DOMAIN}/users/Admin@${PEER_DOMAIN}/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c "cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && bash"
    volumes:
        - /var/run/:/host/var/run/
        - ./../../../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      *depend_service
    networks:
      - fabric
    extra_hosts:
      *hosts
